[module]
[module.hugoVersion]
    min = "0.96.0"

[[module.mounts]]
    source = "archetypes"
    target = "archetypes"

[[module.mounts]]
    source = "assets"
    target = "assets"

[[module.mounts]]
    source = "content"
    target = "content"

[[module.mounts]]
    source = "data"
    target = "data"

[[module.mounts]]
    source = "i18n"
    target = "i18n"

[[module.mounts]]
    source = "layouts"
    target = "layouts"

[[module.mounts]]
    source = "static"
    target = "static"

[[module.mounts]]
    source = "bootstrap/dist/js"
    target = "assets/js"

[[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"

[[module.mounts]]
    source = "bootstrap/scss"
    target = "assets/scss"
